# Site settings
title: Askin Techlabs Private Limited
email: contact@askin.tech
description: Askin Techlabs builds on the latest technologies to build top quality apps for its customers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "askin.tech" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
